ADEVICE plughw:3,0

CHANNEL 0
MYCALL VU3CER

MODEM 1200

PTT CM108

PBEACON delay=0:05 every=1:00 overlay=S symbol="digi" lat=18^27.12N long=073^53.47E power=5 height=10 gain=2 comment="Baofeng APRS Beacon" via=WIDE1-1,WIDE2-1
